theme: "imdhemy-jekyll-theme"
baseurl: "/example"
title: "Imdhemy"
description: "A simple and clean Jekyll theme for your blog"
github:
  build_revision: "1.0.0"

author:
  name: "Dhemy"
  description: |
    I'm a software artist, fullstack (BE heavy) with 10 years of experience in software development. 
    Passionate about open source, blogging, and reading.

navigation:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog"
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"

contributions:
  - name: "Laravel"
    url: "https://laravel.com"
    logo: "/images/theme/laravel.png"

  - name: "Spatie"
    url: "https://spatie.be/open-source"
    logo: "/images/theme/spatie.png"

  - name: "Siklid"
    url: "https://docs.siklid.io/"
    logo: "/images/theme/siklid.png"

  - name: "Google Play Billing"
    url: "https://github.com/imdhemy/google-play-billing"
    logo: "/images/theme/google-play-billing.png"

  - name: "App Store IAP"
    url: "https://github.com/imdhemy/appstore-iap"
    logo: "/images/theme/app-store-iap.png"

  - name: "Laravel In-app Purchase"
    url: "https://imdhemy.com/laravel-iap-docs/"
    logo: "/images/theme/liap.png"

testimonials:
  - name: "John Doe"
    description: "Product Manager"
    image: "https://randomuser.me/api/portraits/med/men/9.jpg"
    content: |
      lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

  - name: "Martha Stewart"
    description: "Frontend Developer"
    image: "https://randomuser.me/api/portraits/med/women/79.jpg"
    content: |
      lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

  - name: "Sandra Bullock"
    description: "Product Manager"
    image: "https://randomuser.me/api/portraits/med/women/21.jpg"
    content: |
      lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

footer:
  bg_image: "/images/theme/social.png"
  social:
    - icon: "logo-github"
      url: "https://github.com/imdhemy"
    - icon: "logo-twitter"
      url: "https://twitter.com/imdhemy"
    - icon: "logo-linkedin"
      url: "https://www.linkedin.com/in/imdhemy/"
    - icon: "logo-youtube"
      url: "https://www.youtube.com/@imdhemy"
