theme: "imdhemy-jekyll-theme"
baseurl: "/example"
title: "Imdhemy"
description: "A simple and clean Jekyll theme for your blog"
github:
  build_revision: "1.0.0"

author:
  name: "Dhemy"
  description: |
    I'm a software artist, fullstack (BE heavy) with 10 years of experience in software development. 
    Passionate about open source, blogging, and reading.

navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"

testimonials:
  - name: "John Doe"
    description: "Product Manager"
    image: "https://randomuser.me/api/portraits/med/men/9.jpg"
    content: |
      lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

  - name: "Martha Stewart"
    description: "Frontend Developer"
    image: "https://randomuser.me/api/portraits/med/women/79.jpg"
    content: |
      lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

  - name: "Sandra Bullock"
    description: "Product Manager"
    image: "https://randomuser.me/api/portraits/med/women/21.jpg"
    content: |
      lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
