theme: "imdhemy-jekyll-theme"
baseurl: "/example"
title: "Imdhemy"
description: "A simple and clean Jekyll theme for your blog"
github:
  build_revision: "1.0.0"

author:
  name: "Dhemy"
  description: |
    I'm a software artist, fullstack (BE heavy) with 10 years of experience in software development. 
    Passionate about open source, blogging, and reading.

navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"

contributions:
  - name: "Laravel"
    url: "https://laravel.com"
    logo: "/images/contributions/adobe.svg"

  - name: "Google Play Billing"
    url: "https://developer.android.com/google/play/billing"
    logo: "/images/contributions/apple.svg"

  - name: "App Store IAP"
    url: "https://developer.apple.com/in-app-purchase/"
    logo: "/images/contributions/google.svg"

  - name: "Laravel In-app Purchase"
    url: "https://imdhemy.com/laravel-iap-docs/"
    logo: "/images/contributions/netlify.svg"

  - name: "Siklid"
    url: "https://docs.siklid.io/"
    logo: "/images/contributions/spotify.svg"

testimonials:
  - name: "John Doe"
    description: "Product Manager"
    image: "https://randomuser.me/api/portraits/med/men/9.jpg"
    content: |
      lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

  - name: "Martha Stewart"
    description: "Frontend Developer"
    image: "https://randomuser.me/api/portraits/med/women/79.jpg"
    content: |
      lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

  - name: "Sandra Bullock"
    description: "Product Manager"
    image: "https://randomuser.me/api/portraits/med/women/21.jpg"
    content: |
      lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
