theme: "imdhemy-jekyll-theme"
baseurl: "/example"
title: "Imdhemy"
description: "A simple and clean Jekyll theme for your blog"
github:
  build_revision: "1.0.0"

author:
  name: "Dhemy"
  description: |
    I'm a software artist, fullstack (BE heavy) with 10 years of experience in software development. 
    Passionate about open source, blogging, and reading.

navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"
